version: '2'

services:
  app:
    build:
      context:  ./app
      dockerfile: Dockerfile
    depends_on:
      - postgres
    expose:
      - "8080"

  postgres:
    image: postgres:11.1-alpine
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    env_file:
      - .env
    ports:
      - "5432:5432"

  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - app
